# Generated by Django 4.0.3 on 2022-03-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantID', models.IntegerField()),
                ('RestaurantName', models.CharField(max_length=555)),
                ('CountryCode', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=555)),
                ('Locality', models.TextField()),
                ('LocalityVerbose', models.TextField()),
                ('Longitude', models.CharField(max_length=555)),
                ('Latitude', models.CharField(max_length=555)),
                ('Cuisines', models.TextField()),
                ('Address', models.TextField()),
                ('AverageCostForTwo', models.CharField(max_length=555)),
                ('Currency', models.CharField(max_length=555)),
                ('PriceRange', models.IntegerField()),
                ('AggregateRating', models.CharField(max_length=555)),
                ('Votes', models.IntegerField()),
            ],
        ),
    ]
