# Generated by Django 4.0.3 on 2022-03-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
