# Generated by Django 4.0.3 on 2022-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DONATOR', 'DONATOR'), ('VOLUNTEER', 'VOLUNTEER')], default='VOLUNTEER', max_length=155),
        ),
    ]
